server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/teebay
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  graphql:
    # single HTTP POST endpoint for all GraphQL operations
    # where to pick up your .graphqls schema files
    schema:
      locations: classpath*:graphql/**/*.graphqls   # :contentReference[oaicite:1]{index=1}

    # enable the dev‐only GraphiQL IDE
    graphiql:
      enabled: true
      path: /graphiql
    http:
      path: /graphql
